[versions]

# Common
kotlin = "2.2.21"

# Plugins
ktlint-plugin = "14.0.1"

# Libraries
kotlinx-coroutines-core = "1.10.2"
kotlinx-immutableCollections = "0.4.0"
kotlinx-datetime = "0.7.1"

junit = "4.13.2"
kotest-assertions = "6.0.5"
coroutinesTest = "1.10.2"


[plugins]
kotlin = { id = "org.jetbrains.kotlin.jvm", version.ref = "kotlin" }
kotlin-powerAssert = { id = "org.jetbrains.kotlin.plugin.power-assert", version.ref = "kotlin"}
ktlint = {id = "org.jlleitschuh.gradle.ktlint", version.ref = "ktlint-plugin"}

[libraries]
kotlin-stdlib = { module = "org.jetbrains.kotlin:kotlin-stdlib", version.ref = "kotlin" }
kotlin-reflect = { module = "org.jetbrains.kotlin:kotlin-reflect", version.ref = "kotlin" }
kotlinx-coroutines-core = { module = "org.jetbrains.kotlinx:kotlinx-coroutines-core", version.ref = "kotlinx-coroutines-core" }
kotlinx-immutableCollections = { module = "org.jetbrains.kotlinx:kotlinx-collections-immutable", version.ref = "kotlinx-immutableCollections" }
kotlinx-datetime = { module = "org.jetbrains.kotlinx:kotlinx-datetime", version.ref = "kotlinx-datetime" }

test-junit = { module = " junit:junit", version.ref = "junit" }
test-kotest-assertions = { module = "io.kotest:kotest-assertions-core", version.ref = "kotest-assertions" }
test-coroutines = { module = " org.jetbrains.kotlinx:kotlinx-coroutines-test", version.ref = "coroutinesTest" }
